name: basic-ci

on: push

jobs:
  linux:
    runs-on: ubuntu-latest
    container: swift:5.5-focal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: SWIFT_DETERMINISTIC_HASHING=1 swift test

  macos:
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2.1'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: SWIFT_DETERMINISTIC_HASHING=1 swift test
